from .file_manager import FileManager
from .web_search import WebSearch
from .code_generator import CodeGenerator
from .weather import Weather
from .news import News
from .email_sender import EmailSender
from .whatsapp import WhatsApp
from .music_player import music
from .system_info import SystemInfo
from .display_control import DisplayControl
from .alarm_timer import alarm_timer
from .calculator import Calculator
from .translator import Translator
from .pdf_reader import PDFReader
from .doc_reader import DocReader
from .clipboard import clipboard
from .network_control import NetworkControl
from .voice_recorder import VoiceRecorder
from .jokes import Jokes
from .datetime_util import DateTimeUtil
from .code_executor import CodeExecutor
from .ocr import OCR
from .calendar_reminder import CalendarReminder
